name: deploy
on:
  pull_request:
    paths:
      - 'x/**'
    types: [closed]
    branches:
      - main
  push:
    branches:
      - main
env:
  SOURCE_DIR: treasurenet/build/treasurenetd
  TARGET_DIR: /home/tnuser
  GO_VERSION: 1.18
jobs:
  build:
    if: github.event.pull_request.merged == true
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up Go version  ${{ env.GO_VERSION }}
        uses: actions/setup-go@v2
        with:
          go-version:  ${{ env.GO_VERSION }}
      - run: go version
      - run: go env -w GO111MODULE=on
      - run: go mod tidy
      - run: make build

      - name: Deploy to Server
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.SERVER_HOST }}
          user: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          connect_timeout: 180s
          first_ssh: |
            sh /home/tnuser/init1.sh
          scp: |
            ${{ env.SOURCE_DIR }} => ${{ env.TARGET_DIR }}
          last_ssh: |
            sh /home/tnuser/deploy-all.sh