name: deploy
on:
  pull_request:
    types:
      - closed
    branches:
      - main
  push:
    branches:
      - main
env:
  SOURCE_DIR: build/treasurenetd
  TARGET_DIR: /home/tnuser
  GO_VERSION: 1.18
jobs:
  build:
    name: build
    runs-on: self-hosted
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go version  ${{ env.GO_VERSION }}
        uses: actions/setup-go@v2
        with:
          go-version:  ${{ env.GO_VERSION }}
      - run: go version
      - run: go env -w GO111MODULE=on
      - run: go mod tidy
      - run: make build

      - name: Deploy to Server
        uses: cross-the-world/ssh-scp-ssh-pipelines@latest
        with:
          host: ${{ secrets.SERVER_HOST }}
          user: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          connect_timeout: 180s
          scp: |
            ${{ env.SOURCE_DIR }} => ${{ env.TARGET_DIR }}