name: Lint
on:
  push:
    branches:
      - main
      - release/**
  pull_request:
  merge_group:
permissions:
  contents: read

jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        
      - uses: DeterminateSystems/nix-installer-action@main

      - uses: DeterminateSystems/magic-nix-cache-action@main

      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          check-latest: true

      - uses: technote-space/get-diff-action@v6.1.2
        id: git_diff_long
        with:
          PATTERNS: |
            Makefile
            **/Makefile
            .golangci.yml

      - name: run linting (long)
        if: steps.git_diff_long.outputs.diff
        id: lint_long
        run: |
          nix develop -c make lint
        env:
          NIX: 1

      - uses: technote-space/get-diff-action@v6.1.2
        if: steps.lint_long.outcome == 'skipped'
        id: git_diff_short
        with:
          PATTERNS: |
            **/*.go
            *.go

      - name: run linting (short)
        if: steps.lint_long.outcome == 'skipped' && steps.git_diff_short.outputs.diff
        run: |
          nix develop -c make lint
        env:
          LINT_DIFF: 1
          NIX: 1
