name: Notify Slack on PR merged to the main branch

on:
  push:
    branches:
      - main

jobs:
  slackNotification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Notify Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }} 
          SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/Octocat.png
          SLACK_MESSAGE: ${{ github.event.pull_request.title }} merged to main branch
          SLACK_COLOR: '#00FF00'